server:
  port: 9001
  
spring:
  application:
    name: adtec-cloud-config-client
  
info:
  app:
    name: ${spring.application.name}
    version: 1.0.0
    
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
    httptrace:
      enabled: true
