server:
  port: 9002
  
spring:
  application:
    name: adtec-cloud-consumer
  
info:
  app:
    name: ${spring.application.name}
    version: 1.0.0
    
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
    httptrace:
      enabled: true
#预加载配置,默认为懒加载
ribbon:
  ReadTimeout: 5000
  SocketTimeout: 5000
  eager-load:
    enabled: true
    clients:
    - adtec-cloud-producer


adtec-cloud-producer:
  ribbon:
    # 代表Ribbon使用的负载均衡策略
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.WeightedResponseTimeRule
    # Max number of retries on the same server (excluding the first try)
    MaxAutoRetries: 1
    # Max number of next servers to retry (excluding the first server)
    MaxAutoRetriesNextServer: 1
    # Whether all operations can be retried for this client
    OkToRetryOnAllOperations: true
    # Interval to refresh the server list from the source
    ServerListRefreshInterval: 2000
    # Connect timeout used by Apache HttpClient
    ConnectTimeout: 3000
    # Read timeout used by Apache HttpClient
    ReadTimeout: 3000

logging:
  level:
    '[com.adtec.cloud.consumer.feign.UserFeignClient]': DEBUG

feign:
  hystrix:
    enabled: true
